// Code generated by MockGen. DO NOT EDIT.
// Source: user.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	models "github.com/zahartd/social-network/src/services/user-service/internal/domain/models"
)

// MockEventPublisher is a mock of EventPublisher interface.
type MockEventPublisher struct {
	ctrl     *gomock.Controller
	recorder *MockEventPublisherMockRecorder
}

// MockEventPublisherMockRecorder is the mock recorder for MockEventPublisher.
type MockEventPublisherMockRecorder struct {
	mock *MockEventPublisher
}

// NewMockEventPublisher creates a new mock instance.
func NewMockEventPublisher(ctrl *gomock.Controller) *MockEventPublisher {
	mock := &MockEventPublisher{ctrl: ctrl}
	mock.recorder = &MockEventPublisherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEventPublisher) EXPECT() *MockEventPublisherMockRecorder {
	return m.recorder
}

// PublishUserRegistered mocks base method.
func (m *MockEventPublisher) PublishUserRegistered(ctx context.Context, ev models.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishUserRegistered", ctx, ev)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishUserRegistered indicates an expected call of PublishUserRegistered.
func (mr *MockEventPublisherMockRecorder) PublishUserRegistered(ctx, ev interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishUserRegistered", reflect.TypeOf((*MockEventPublisher)(nil).PublishUserRegistered), ctx, ev)
}
