// Code generated by avro/gen. DO NOT EDIT.
package events

import (
	"time"

	"github.com/hamba/avro/v2"
)

// UserRegistered is a generated struct.
type UserRegistered struct {
	UserID    string    `avro:"user_id"`
	Email     string    `avro:"email"`
	CreatedAt time.Time `avro:"created_at"`
}

var schemaUserRegistered = avro.MustParse(`{"name":"com.example.users.UserRegistered","type":"record","fields":[{"name":"user_id","type":"string"},{"name":"email","type":"string"},{"name":"created_at","type":{"type":"long","logicalType":"timestamp-millis"}}]}`)

// Schema returns the schema for UserRegistered.
func (o *UserRegistered) Schema() avro.Schema {
	return schemaUserRegistered
}

// Unmarshal decodes b into the receiver.
func (o *UserRegistered) Unmarshal(b []byte) error {
	return avro.Unmarshal(o.Schema(), b, o)
}

// Marshal encodes the receiver.
func (o *UserRegistered) Marshal() ([]byte, error) {
	return avro.Marshal(o.Schema(), o)
}
