// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: stats/stats.proto

package stats

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetDynamicsRequest_Metric int32

const (
	GetDynamicsRequest_VIEWS    GetDynamicsRequest_Metric = 0
	GetDynamicsRequest_LIKES    GetDynamicsRequest_Metric = 1
	GetDynamicsRequest_COMMENTS GetDynamicsRequest_Metric = 2
)

// Enum value maps for GetDynamicsRequest_Metric.
var (
	GetDynamicsRequest_Metric_name = map[int32]string{
		0: "VIEWS",
		1: "LIKES",
		2: "COMMENTS",
	}
	GetDynamicsRequest_Metric_value = map[string]int32{
		"VIEWS":    0,
		"LIKES":    1,
		"COMMENTS": 2,
	}
)

func (x GetDynamicsRequest_Metric) Enum() *GetDynamicsRequest_Metric {
	p := new(GetDynamicsRequest_Metric)
	*p = x
	return p
}

func (x GetDynamicsRequest_Metric) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GetDynamicsRequest_Metric) Descriptor() protoreflect.EnumDescriptor {
	return file_stats_stats_proto_enumTypes[0].Descriptor()
}

func (GetDynamicsRequest_Metric) Type() protoreflect.EnumType {
	return &file_stats_stats_proto_enumTypes[0]
}

func (x GetDynamicsRequest_Metric) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GetDynamicsRequest_Metric.Descriptor instead.
func (GetDynamicsRequest_Metric) EnumDescriptor() ([]byte, []int) {
	return file_stats_stats_proto_rawDescGZIP(), []int{2, 0}
}

type GetTopRequest_By int32

const (
	GetTopRequest_VIEWS    GetTopRequest_By = 0
	GetTopRequest_LIKES    GetTopRequest_By = 1
	GetTopRequest_COMMENTS GetTopRequest_By = 2
)

// Enum value maps for GetTopRequest_By.
var (
	GetTopRequest_By_name = map[int32]string{
		0: "VIEWS",
		1: "LIKES",
		2: "COMMENTS",
	}
	GetTopRequest_By_value = map[string]int32{
		"VIEWS":    0,
		"LIKES":    1,
		"COMMENTS": 2,
	}
)

func (x GetTopRequest_By) Enum() *GetTopRequest_By {
	p := new(GetTopRequest_By)
	*p = x
	return p
}

func (x GetTopRequest_By) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GetTopRequest_By) Descriptor() protoreflect.EnumDescriptor {
	return file_stats_stats_proto_enumTypes[1].Descriptor()
}

func (GetTopRequest_By) Type() protoreflect.EnumType {
	return &file_stats_stats_proto_enumTypes[1]
}

func (x GetTopRequest_By) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GetTopRequest_By.Descriptor instead.
func (GetTopRequest_By) EnumDescriptor() ([]byte, []int) {
	return file_stats_stats_proto_rawDescGZIP(), []int{5, 0}
}

type GetPostStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        string                 `protobuf:"bytes,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPostStatsRequest) Reset() {
	*x = GetPostStatsRequest{}
	mi := &file_stats_stats_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPostStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPostStatsRequest) ProtoMessage() {}

func (x *GetPostStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stats_stats_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPostStatsRequest.ProtoReflect.Descriptor instead.
func (*GetPostStatsRequest) Descriptor() ([]byte, []int) {
	return file_stats_stats_proto_rawDescGZIP(), []int{0}
}

func (x *GetPostStatsRequest) GetPostId() string {
	if x != nil {
		return x.PostId
	}
	return ""
}

type GetPostStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Views         int64                  `protobuf:"varint,1,opt,name=views,proto3" json:"views,omitempty"`
	Likes         int64                  `protobuf:"varint,2,opt,name=likes,proto3" json:"likes,omitempty"`
	Comments      int64                  `protobuf:"varint,3,opt,name=comments,proto3" json:"comments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPostStatsResponse) Reset() {
	*x = GetPostStatsResponse{}
	mi := &file_stats_stats_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPostStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPostStatsResponse) ProtoMessage() {}

func (x *GetPostStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stats_stats_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPostStatsResponse.ProtoReflect.Descriptor instead.
func (*GetPostStatsResponse) Descriptor() ([]byte, []int) {
	return file_stats_stats_proto_rawDescGZIP(), []int{1}
}

func (x *GetPostStatsResponse) GetViews() int64 {
	if x != nil {
		return x.Views
	}
	return 0
}

func (x *GetPostStatsResponse) GetLikes() int64 {
	if x != nil {
		return x.Likes
	}
	return 0
}

func (x *GetPostStatsResponse) GetComments() int64 {
	if x != nil {
		return x.Comments
	}
	return 0
}

type GetDynamicsRequest struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	PostId        string                    `protobuf:"bytes,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	Metric        GetDynamicsRequest_Metric `protobuf:"varint,2,opt,name=metric,proto3,enum=stats.GetDynamicsRequest_Metric" json:"metric,omitempty"` // опционально: date_from, date_to
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDynamicsRequest) Reset() {
	*x = GetDynamicsRequest{}
	mi := &file_stats_stats_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDynamicsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDynamicsRequest) ProtoMessage() {}

func (x *GetDynamicsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stats_stats_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDynamicsRequest.ProtoReflect.Descriptor instead.
func (*GetDynamicsRequest) Descriptor() ([]byte, []int) {
	return file_stats_stats_proto_rawDescGZIP(), []int{2}
}

func (x *GetDynamicsRequest) GetPostId() string {
	if x != nil {
		return x.PostId
	}
	return ""
}

func (x *GetDynamicsRequest) GetMetric() GetDynamicsRequest_Metric {
	if x != nil {
		return x.Metric
	}
	return GetDynamicsRequest_VIEWS
}

type DayCount struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Date          string                 `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"` // "YYYY-MM-DD"
	Count         int64                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DayCount) Reset() {
	*x = DayCount{}
	mi := &file_stats_stats_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DayCount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DayCount) ProtoMessage() {}

func (x *DayCount) ProtoReflect() protoreflect.Message {
	mi := &file_stats_stats_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DayCount.ProtoReflect.Descriptor instead.
func (*DayCount) Descriptor() ([]byte, []int) {
	return file_stats_stats_proto_rawDescGZIP(), []int{3}
}

func (x *DayCount) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *DayCount) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type GetDynamicsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*DayCount            `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDynamicsResponse) Reset() {
	*x = GetDynamicsResponse{}
	mi := &file_stats_stats_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDynamicsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDynamicsResponse) ProtoMessage() {}

func (x *GetDynamicsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stats_stats_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDynamicsResponse.ProtoReflect.Descriptor instead.
func (*GetDynamicsResponse) Descriptor() ([]byte, []int) {
	return file_stats_stats_proto_rawDescGZIP(), []int{4}
}

func (x *GetDynamicsResponse) GetData() []*DayCount {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetTopRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	By            GetTopRequest_By       `protobuf:"varint,1,opt,name=by,proto3,enum=stats.GetTopRequest_By" json:"by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTopRequest) Reset() {
	*x = GetTopRequest{}
	mi := &file_stats_stats_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTopRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTopRequest) ProtoMessage() {}

func (x *GetTopRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stats_stats_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTopRequest.ProtoReflect.Descriptor instead.
func (*GetTopRequest) Descriptor() ([]byte, []int) {
	return file_stats_stats_proto_rawDescGZIP(), []int{5}
}

func (x *GetTopRequest) GetBy() GetTopRequest_By {
	if x != nil {
		return x.By
	}
	return GetTopRequest_VIEWS
}

type TopPost struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        string                 `protobuf:"bytes,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	Count         int64                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopPost) Reset() {
	*x = TopPost{}
	mi := &file_stats_stats_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopPost) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopPost) ProtoMessage() {}

func (x *TopPost) ProtoReflect() protoreflect.Message {
	mi := &file_stats_stats_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopPost.ProtoReflect.Descriptor instead.
func (*TopPost) Descriptor() ([]byte, []int) {
	return file_stats_stats_proto_rawDescGZIP(), []int{6}
}

func (x *TopPost) GetPostId() string {
	if x != nil {
		return x.PostId
	}
	return ""
}

func (x *TopPost) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type TopUser struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Count         int64                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopUser) Reset() {
	*x = TopUser{}
	mi := &file_stats_stats_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopUser) ProtoMessage() {}

func (x *TopUser) ProtoReflect() protoreflect.Message {
	mi := &file_stats_stats_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopUser.ProtoReflect.Descriptor instead.
func (*TopUser) Descriptor() ([]byte, []int) {
	return file_stats_stats_proto_rawDescGZIP(), []int{7}
}

func (x *TopUser) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *TopUser) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type TopPostsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*TopPost             `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"` // top 10
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopPostsResponse) Reset() {
	*x = TopPostsResponse{}
	mi := &file_stats_stats_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopPostsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopPostsResponse) ProtoMessage() {}

func (x *TopPostsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stats_stats_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopPostsResponse.ProtoReflect.Descriptor instead.
func (*TopPostsResponse) Descriptor() ([]byte, []int) {
	return file_stats_stats_proto_rawDescGZIP(), []int{8}
}

func (x *TopPostsResponse) GetItems() []*TopPost {
	if x != nil {
		return x.Items
	}
	return nil
}

type TopUsersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*TopUser             `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopUsersResponse) Reset() {
	*x = TopUsersResponse{}
	mi := &file_stats_stats_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopUsersResponse) ProtoMessage() {}

func (x *TopUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stats_stats_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopUsersResponse.ProtoReflect.Descriptor instead.
func (*TopUsersResponse) Descriptor() ([]byte, []int) {
	return file_stats_stats_proto_rawDescGZIP(), []int{9}
}

func (x *TopUsersResponse) GetItems() []*TopUser {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_stats_stats_proto protoreflect.FileDescriptor

const file_stats_stats_proto_rawDesc = "" +
	"\n" +
	"\x11stats/stats.proto\x12\x05stats\".\n" +
	"\x13GetPostStatsRequest\x12\x17\n" +
	"\apost_id\x18\x01 \x01(\tR\x06postId\"^\n" +
	"\x14GetPostStatsResponse\x12\x14\n" +
	"\x05views\x18\x01 \x01(\x03R\x05views\x12\x14\n" +
	"\x05likes\x18\x02 \x01(\x03R\x05likes\x12\x1a\n" +
	"\bcomments\x18\x03 \x01(\x03R\bcomments\"\x95\x01\n" +
	"\x12GetDynamicsRequest\x12\x17\n" +
	"\apost_id\x18\x01 \x01(\tR\x06postId\x128\n" +
	"\x06metric\x18\x02 \x01(\x0e2 .stats.GetDynamicsRequest.MetricR\x06metric\",\n" +
	"\x06Metric\x12\t\n" +
	"\x05VIEWS\x10\x00\x12\t\n" +
	"\x05LIKES\x10\x01\x12\f\n" +
	"\bCOMMENTS\x10\x02\"4\n" +
	"\bDayCount\x12\x12\n" +
	"\x04date\x18\x01 \x01(\tR\x04date\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x03R\x05count\":\n" +
	"\x13GetDynamicsResponse\x12#\n" +
	"\x04data\x18\x01 \x03(\v2\x0f.stats.DayCountR\x04data\"b\n" +
	"\rGetTopRequest\x12'\n" +
	"\x02by\x18\x01 \x01(\x0e2\x17.stats.GetTopRequest.ByR\x02by\"(\n" +
	"\x02By\x12\t\n" +
	"\x05VIEWS\x10\x00\x12\t\n" +
	"\x05LIKES\x10\x01\x12\f\n" +
	"\bCOMMENTS\x10\x02\"8\n" +
	"\aTopPost\x12\x17\n" +
	"\apost_id\x18\x01 \x01(\tR\x06postId\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x03R\x05count\"8\n" +
	"\aTopUser\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x03R\x05count\"8\n" +
	"\x10TopPostsResponse\x12$\n" +
	"\x05items\x18\x01 \x03(\v2\x0e.stats.TopPostR\x05items\"8\n" +
	"\x10TopUsersResponse\x12$\n" +
	"\x05items\x18\x01 \x03(\v2\x0e.stats.TopUserR\x05items2\x9d\x02\n" +
	"\fStatsService\x12G\n" +
	"\fGetPostStats\x12\x1a.stats.GetPostStatsRequest\x1a\x1b.stats.GetPostStatsResponse\x12H\n" +
	"\x0fGetPostDynamics\x12\x19.stats.GetDynamicsRequest\x1a\x1a.stats.GetDynamicsResponse\x12<\n" +
	"\vGetTopPosts\x12\x14.stats.GetTopRequest\x1a\x17.stats.TopPostsResponse\x12<\n" +
	"\vGetTopUsers\x12\x14.stats.GetTopRequest\x1a\x17.stats.TopUsersResponseB5Z3github.com/zahartd/social-network/src/grpc/go/statsb\x06proto3"

var (
	file_stats_stats_proto_rawDescOnce sync.Once
	file_stats_stats_proto_rawDescData []byte
)

func file_stats_stats_proto_rawDescGZIP() []byte {
	file_stats_stats_proto_rawDescOnce.Do(func() {
		file_stats_stats_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_stats_stats_proto_rawDesc), len(file_stats_stats_proto_rawDesc)))
	})
	return file_stats_stats_proto_rawDescData
}

var file_stats_stats_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_stats_stats_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_stats_stats_proto_goTypes = []any{
	(GetDynamicsRequest_Metric)(0), // 0: stats.GetDynamicsRequest.Metric
	(GetTopRequest_By)(0),          // 1: stats.GetTopRequest.By
	(*GetPostStatsRequest)(nil),    // 2: stats.GetPostStatsRequest
	(*GetPostStatsResponse)(nil),   // 3: stats.GetPostStatsResponse
	(*GetDynamicsRequest)(nil),     // 4: stats.GetDynamicsRequest
	(*DayCount)(nil),               // 5: stats.DayCount
	(*GetDynamicsResponse)(nil),    // 6: stats.GetDynamicsResponse
	(*GetTopRequest)(nil),          // 7: stats.GetTopRequest
	(*TopPost)(nil),                // 8: stats.TopPost
	(*TopUser)(nil),                // 9: stats.TopUser
	(*TopPostsResponse)(nil),       // 10: stats.TopPostsResponse
	(*TopUsersResponse)(nil),       // 11: stats.TopUsersResponse
}
var file_stats_stats_proto_depIdxs = []int32{
	0,  // 0: stats.GetDynamicsRequest.metric:type_name -> stats.GetDynamicsRequest.Metric
	5,  // 1: stats.GetDynamicsResponse.data:type_name -> stats.DayCount
	1,  // 2: stats.GetTopRequest.by:type_name -> stats.GetTopRequest.By
	8,  // 3: stats.TopPostsResponse.items:type_name -> stats.TopPost
	9,  // 4: stats.TopUsersResponse.items:type_name -> stats.TopUser
	2,  // 5: stats.StatsService.GetPostStats:input_type -> stats.GetPostStatsRequest
	4,  // 6: stats.StatsService.GetPostDynamics:input_type -> stats.GetDynamicsRequest
	7,  // 7: stats.StatsService.GetTopPosts:input_type -> stats.GetTopRequest
	7,  // 8: stats.StatsService.GetTopUsers:input_type -> stats.GetTopRequest
	3,  // 9: stats.StatsService.GetPostStats:output_type -> stats.GetPostStatsResponse
	6,  // 10: stats.StatsService.GetPostDynamics:output_type -> stats.GetDynamicsResponse
	10, // 11: stats.StatsService.GetTopPosts:output_type -> stats.TopPostsResponse
	11, // 12: stats.StatsService.GetTopUsers:output_type -> stats.TopUsersResponse
	9,  // [9:13] is the sub-list for method output_type
	5,  // [5:9] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_stats_stats_proto_init() }
func file_stats_stats_proto_init() {
	if File_stats_stats_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_stats_stats_proto_rawDesc), len(file_stats_stats_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_stats_stats_proto_goTypes,
		DependencyIndexes: file_stats_stats_proto_depIdxs,
		EnumInfos:         file_stats_stats_proto_enumTypes,
		MessageInfos:      file_stats_stats_proto_msgTypes,
	}.Build()
	File_stats_stats_proto = out.File
	file_stats_stats_proto_goTypes = nil
	file_stats_stats_proto_depIdxs = nil
}
