// Code generated by avro/gen. DO NOT EDIT.
package events

import (
	"time"

	"github.com/hamba/avro/v2"
)

// LikedPostEvent is a generated struct.
type LikedPostEvent struct {
	UserID  string    `avro:"user_id"`
	PostID  string    `avro:"post_id"`
	LikedAt time.Time `avro:"liked_at"`
}

var schemaLikedPostEvent = avro.MustParse(`{"name":"com.example.events.LikedPostEvent","type":"record","fields":[{"name":"user_id","type":"string"},{"name":"post_id","type":"string"},{"name":"liked_at","type":{"type":"long","logicalType":"timestamp-millis"}}]}`)

// Schema returns the schema for LikedPostEvent.
func (o *LikedPostEvent) Schema() avro.Schema {
	return schemaLikedPostEvent
}

// Unmarshal decodes b into the receiver.
func (o *LikedPostEvent) Unmarshal(b []byte) error {
	return avro.Unmarshal(o.Schema(), b, o)
}

// Marshal encodes the receiver.
func (o *LikedPostEvent) Marshal() ([]byte, error) {
	return avro.Marshal(o.Schema(), o)
}
