// Code generated by avro/gen. DO NOT EDIT.
package events

import (
	"time"

	"github.com/hamba/avro/v2"
)

// ViewedPostEvent is a generated struct.
type ViewedPostEvent struct {
	UserID   string    `avro:"user_id"`
	PostID   string    `avro:"post_id"`
	ViewedAt time.Time `avro:"viewed_at"`
}

var schemaViewedPostEvent = avro.MustParse(`{"name":"com.example.events.ViewedPostEvent","type":"record","fields":[{"name":"user_id","type":"string"},{"name":"post_id","type":"string"},{"name":"viewed_at","type":{"type":"long","logicalType":"timestamp-millis"}}]}`)

// Schema returns the schema for ViewedPostEvent.
func (o *ViewedPostEvent) Schema() avro.Schema {
	return schemaViewedPostEvent
}

// Unmarshal decodes b into the receiver.
func (o *ViewedPostEvent) Unmarshal(b []byte) error {
	return avro.Unmarshal(o.Schema(), b, o)
}

// Marshal encodes the receiver.
func (o *ViewedPostEvent) Marshal() ([]byte, error) {
	return avro.Marshal(o.Schema(), o)
}
